import type { AppSettings, Client, Report, SectionBlock } from "@/types/imani";

function blockText(block: SectionBlock) {
  if (block.type === "richText") return block.content;
  if (block.type === "checklist")
    return block.items.map((i) => `- ${i.checked ? "[x]" : "[ ]"} ${i.text}`).join("\n");
  if (block.type === "kpi")
    return block.items
      .map((i) => `${i.name}: ${i.value}${i.unit ? ` ${i.unit}` : ""}`)
      .join("\n");
  if (block.type === "score") return `${block.value}/${block.max}${block.note ? ` — ${block.note}` : ""}`;
  if (block.type === "table") return `${block.columns.join(" | ")}\n${block.rows.map((r) => r.join(" | ")).join("\n")}`;
  if (block.type === "image") return block.url;
  return "";
}

export function ReportPrintView({
  report,
  client,
  settings,
}: {
  report: Report;
  client: Client;
  settings: AppSettings;
}) {
  return (
    <div className="w-[816px] bg-white text-[#031111]">
      {/* Cover */}
      <div className="min-h-[1056px] p-12">
        <div className="flex items-center justify-between">
          <div>
            <div className="text-sm font-semibold tracking-tight text-[#185391]">
              {settings.agencyName}
            </div>
            <div className="mt-1 text-3xl font-semibold tracking-tight">
              {report.title}
            </div>
            <div className="mt-2 text-sm text-[#031111]/70">
              {client.name}
              {report.reportingPeriod ? ` • ${report.reportingPeriod}` : ""}
            </div>
          </div>
          <div
            className="h-12 w-12 rounded-3xl"
            style={{
              background: "linear-gradient(135deg, #26bbc0, #185391)",
            }}
          />
        </div>

        <div className="mt-10 grid grid-cols-2 gap-6">
          <div className="rounded-2xl border border-[#e6f0f0] bg-[#eefcfc] p-5">
            <div className="text-xs font-semibold uppercase tracking-wide text-[#185391]">
              Prepared for
            </div>
            <div className="mt-2 text-lg font-semibold">{client.name}</div>
            <div className="mt-2 text-sm text-[#031111]/75">
              {[client.city, client.state].filter(Boolean).join(", ") || "—"}
            </div>
          </div>
          <div className="rounded-2xl border border-[#e6f0f0] bg-white p-5">
            <div className="text-xs font-semibold uppercase tracking-wide text-[#185391]">
              Report details
            </div>
            <div className="mt-2 text-sm">
              <div>
                <span className="font-semibold">Type:</span> {report.reportType}
              </div>
              <div className="mt-1">
                <span className="font-semibold">Status:</span> {report.status}
              </div>
              <div className="mt-1">
                <span className="font-semibold">Analyst:</span> {report.analyst || "—"}
              </div>
              <div className="mt-1">
                <span className="font-semibold">Created:</span> {new Date(report.createdAt).toLocaleDateString()}
              </div>
            </div>
          </div>
        </div>

        {report.executiveSummary ? (
          <div className="mt-10 rounded-2xl border border-[#e6f0f0] p-6">
            <div className="text-xs font-semibold uppercase tracking-wide text-[#185391]">
              Executive summary
            </div>
            <div className="mt-3 whitespace-pre-wrap text-sm leading-6">
              {report.executiveSummary}
            </div>
          </div>
        ) : null}

        <div className="mt-10 text-xs text-[#031111]/60">
          Generated by Imani OS • {settings.agencyName}
        </div>
      </div>

      {/* Sections */}
      {report.sections.map((s) => (
        <div key={s.id} className="min-h-[1056px] break-after-page p-12">
          <div className="flex items-end justify-between">
            <div>
              <div className="text-xs font-semibold uppercase tracking-wide text-[#185391]">
                Section
              </div>
              <div className="mt-1 text-2xl font-semibold tracking-tight">{s.title}</div>
            </div>
            <div className="text-xs text-[#031111]/60">{client.name}</div>
          </div>

          <div className="mt-6 space-y-4">
            {s.blocks.map((b) => (
              <div key={b.id} className="rounded-2xl border border-[#e6f0f0] p-5">
                <div className="text-xs font-semibold uppercase tracking-wide text-[#185391]">
                  {b.label}
                </div>
                {b.type === "image" ? (
                  <div className="mt-3">
                    {/* External images will render if CORS allows; otherwise the URL will still appear. */}
                    <img
                      src={b.url}
                      alt={b.caption || b.label}
                      className="max-h-80 w-full rounded-xl object-cover"
                    />
                    {b.caption ? (
                      <div className="mt-2 text-xs text-[#031111]/60">{b.caption}</div>
                    ) : null}
                  </div>
                ) : (
                  <div className="mt-3 whitespace-pre-wrap text-sm leading-6">
                    {blockText(b)}
                  </div>
                )}
              </div>
            ))}

            {s.internalNotes ? (
              <div className="rounded-2xl border border-[#e6f0f0] bg-[#eefcfc] p-5">
                <div className="text-xs font-semibold uppercase tracking-wide text-[#185391]">
                  Internal notes
                </div>
                <div className="mt-3 whitespace-pre-wrap text-sm leading-6">
                  {s.internalNotes}
                </div>
              </div>
            ) : null}
          </div>

          {report.nextSteps ? (
            <div className="mt-8 rounded-2xl border border-[#e6f0f0] p-6">
              <div className="text-xs font-semibold uppercase tracking-wide text-[#185391]">
                Optional next steps
              </div>
              <div className="mt-3 whitespace-pre-wrap text-sm leading-6">
                {report.nextSteps}
              </div>
            </div>
          ) : null}
        </div>
      ))}
    </div>
  );
}
